[package]
name = "fmodel-rust-demo"
version = "0.1.0"
edition = "2021"
authors = ["Ivan Dugalic <ivan.dugalic@fraktalio.com>"]


[dependencies]
fmodel-rust = "0.5.0"
async-trait = "0.1.74"
actix-cors = "0.6.5"
actix-web = "4.4.0"
actix-rt = "2.9.0"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
tokio = {version = "1.35.1", features = ["full"]}
chrono = {version = "0.4.31", features = ["serde"]}
sqlx = {version = "0.7.3", features = ["postgres", "runtime-tokio", "chrono", "uuid", "macros", "json"]}
uuid = { version = "1.6.1", features = ["serde", "v4"] }
dotenv = "0.15.0"
env_logger = "0.10.1"
log = "0.4.20"
